# Generated by Django 2.0.6 on 2018-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docidentificacao',
            options={'verbose_name': 'Doc. Identificações'},
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
